services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: bitlibrary1549
      MYSQL_DATABASE: bitlibrary
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  spring-boot:
    build: .
    image: spring-boot-bitlibrary
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx500m
    networks:
      - springboot-mysql-net
    depends_on:
      - db
    restart: always

networks:
  springboot-mysql-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
