spring:
#  mvc:
#    pathmatch:
#     use-trailing-slash-match: true
       #  mvc:
       #    pathmatch:
      #      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/bitlibrary
    username: aa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug